name: development CI/CD

on:
  push:
    branches:
      - develop # develop 브랜치에 "push"될 때만 본 workflow를 실행

jobs:
  preview:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout branch # 레포지토리 소스를 runner로 가져오기
        uses: actions/checkout@v3
      - name: Build
        run: yarn && yarn build
      - name: Deploy to Firebase Hosting preview channel
        id: firebase_hosting_preview
        uses: FirebaseExtended/action-hosting-deploy@v0 # firebase 배포를 위한 action
        with:
          repoToken: "${{ secrets.EASY_TICKET }}" # github token
          firebaseServiceAccount: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" # 레포지토리 환경변수로 등록한 firebase service account
          channelId: develop # firebase preview channel의 ID, channelId 필드를 넣어주면 preview 채널로 배포되게 된다.
          expires: 30d # preview 만료기간
          projectId: easy-ticket-e7da7 # FireBase 프로젝트 ID
      - name: Check outputs
        run: |
          echo urls ${{steps.firebase_hosting_preview.outputs.url}}
          echo expire_time ${{steps.firebase_hosting_preview.outputs.expire_time}}
          echo details_url ${{steps.firebase_hosting_preview.outputs.details_url}}
